routes/admin.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/



Route::get('/login','Admin\Auth\UsersController@index');
Route::post('/postLogin','Admin\Auth\UsersController@postLogin')->name('postLogin');
Route::group([ 'middleware' => \App\Http\Middleware\RedirectIfAuthenticated::class],function() {
    Route::get('logout','Admin\Auth\UsersController@logout')->name('logout');
    Route::get('dashboard','Admin\Dashboard\DashboardController@index')->name('dashboard');
    Route::get('/','Admin\Dashboard\DashboardController@index');
    Route::group(['middleware' => \App\Http\Middleware\DisablePreventLogout::class], function () {
        Route::group(['prefix' => 'admin-users'], function () {
            Route::get('/', 'Admin\Auth\UsersController@userIndex')->name('adminUsers');
            Route::get('/datatableList', 'Admin\Auth\UsersController@userList')->name('adminUserDatatableList');
            Route::get('/create', 'Admin\Auth\UsersController@create')->name('adminUsers.create');
            Route::post('/save/{id?}', 'Admin\Auth\UsersController@save')->name('adminUsers.save');
            Route::get('/view/{id}', 'Admin\Auth\UsersController@view')->name('adminUsers.view');
            Route::get('/edit/{id}', 'Admin\Auth\UsersController@edit')->name('adminUsers.edit');
            Route::get('/delete/{id}', 'Admin\Auth\UsersController@delete')->name('adminUsers.delete');
        });
        Route::group(['prefix' => 'role'], function () {
            Route::get('/', 'Admin\Auth\RolesController@index')->name('roles');
            Route::get('/datatableList', 'Admin\Auth\RolesController@datatableList')->name('rolesDatatableList');
            Route::get('/create/', 'Admin\Auth\RolesController@create')->name('roles.create');
            Route::get('/edit/{id}', 'Admin\Auth\RolesController@edit')->name('roles.edit');
            Route::get('/view/{id}', 'Admin\Auth\RolesController@view')->name('roles.view');
            Route::post('/save/{id?}', 'Admin\Auth\RolesController@save')->name('roles.save');
            Route::get('/delete/{id}', 'Admin\Auth\RolesController@delete')->name('roles.delete');
        });
        Route::group(['prefix' => 'employee'], function () {
            Route::get('/', 'Admin\Employee\EmployeeController@index')->name('employee.list');
            Route::get('/datatableList', 'Admin\Employee\EmployeeController@employeesList')->name('employeeDatatableList');
            Route::get('/create', 'Admin\Employee\EmployeeController@create')->name('employee.create');
            Route::post('/save/{id?}', 'Admin\Employee\EmployeeController@save')->name('employee.save');
            Route::get('/view/{id}', 'Admin\Employee\EmployeeController@view')->name('employee.view');
            Route::get('/edit/{id}', 'Admin\Employee\EmployeeController@edit')->name('employee.edit');
            Route::get('/delete/{id}', 'Admin\Employee\EmployeeController@delete')->name('employee.delete');
        });

        Route::group(['prefix' => 'image'], function () {
            Route::get('/', 'Admin\Image\ImageController@index')->name('images.list');
            Route::get('/datatableList', 'Admin\Image\ImageController@imagesList')->name('imagesDatatableList');
            Route::get('/delete/{id}', 'Admin\Image\ImageController@delete')->name('images.delete');
            Route::post('/save/', 'Admin\Image\ImageController@save')->name('images.save');
        });

        Route::group(['prefix' => 'permission'], function () {
            Route::get('/', 'Admin\Auth\PermissionsController@index')->name('permissions');
            Route::get('/datatableList', 'Admin\Auth\PermissionsController@datatableList')->name('permissionsDatatableList');
            Route::get('/create/', 'Admin\Auth\PermissionsController@create')->name('permissions.create');
            Route::get('/edit/{id}', 'Admin\Auth\PermissionsController@edit')->name('permissions.edit');
            Route::get('/view/{id}', 'Admin\Auth\PermissionsController@view')->name('permissions.view');
            Route::post('/save/{id?}', 'Admin\Auth\PermissionsController@save')->name('permissions.save');
            Route::get('/delete/{id}', 'Admin\Auth\PermissionsController@delete')->name('permissions.delete');
        });
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('index.php/admin');
//    return view('welcome');
});

app/User.php
<?php

namespace App;

use App\Models\Roles;
use App\Models\RoleUsers;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\File;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'username',
        'active',
        'slug',
        'bio',
        'is_admin',
        'device_id',
        'device_name',
        'is_employee',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function getImagePathAttribute(){
        return public_path($this->image_dir);
    }
    public function getImageDirAttribute(){
        return 'uploads/user/'.$this->id.'/';
    }
    public function getImageUrlAttribute(){
        return  asset('public/'.$this->image_dir.'/avatar.png');
    }
    public  function uploadImage(){
        if(request()->file('image')) {
            $this->unlinkImage();
            uploadImage(request()->file('image'), $this->image_path, 'avatar.png', '250', '');
        }
    }
    public  function unlinkImage(){
        if(File::exists($this->image_path.'/avatar.png')){

            File::delete($this->image_path.'/avatar.png');
        }

    }
    public function getRoleIdsAttribute(){
        return  RoleUsers::where('user_id',$this->id)->get()->pluck('role_id')->toArray();
    }
    public function getRoleNamesAttribute(){
        return   Roles::whereIn('id',$this->role_ids)->get()->pluck('name')->toArray();
    }
    public function getCheckFileExistsAttribute(){
        return File::exists($this->image_path.'/avatar.png');
    }
}

app/Http/Controllers/Admin/Employee/EmployeeController.php
<?php

namespace App\Http\Controllers\Admin\Employee;

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Controller;
use App\Models\Roles;
use App\Models\RoleUsers;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\Facades\DataTables;

class EmployeeController extends AdminController
{
    public function index(){
        if(checkPermission('admin.employee.users.list')){
            $this->setDatatableJSCSS();
            $breadcrumbData = [
                [
                    'title'=>'Dashboard',
                    'url' => route('dashboard'),
                    'active' => false,
                ],
                [
                    'title' => 'Employees',
                    'url'=> '#',
                    'active'=> true,
                ]
            ];

            return view('Admin.Employee.index',[
                'page_title' =>'Employees',
                'menu' => 'employee',
                'breadcrumbData'=> $breadcrumbData,
            ]);

        }else{
            return Redirect::back()->with(['msg_type'=>'error','msg'=>'you are not allowed to access']);
        }
    }
    public function employeesList(Request $request){

        return DataTables::eloquent(User::query()->whereNotIn('id',[Auth::user()->id])->where('is_employee',1))
            ->editColumn('name',function ($query){
                return '<strong>'.$query->name.'</strong>';
//                return ($query->check_file_exists ? '<img src="'.$query->thumbnail_url.'" style="width:100%;"/>':'').'<strong>'.$query->name.'</strong>';
            })
            ->addColumn('action', function ($query) {
                $links = '';
                if(checkPermission('admin.employee.users.update')) {
                    $links .= '<a data-toggle="tooltip" title="Edit" href="' . route('employee.edit', $query->id) . '" class="btn btn-sm btn-primary-custom"> <i class="fa fa-edit"></i></a>';
                }
                if(checkPermission('admin.employee.users.view')) {
                    $links .= '&nbsp;<a data-toggle="tooltip" title="View" href="' . route('employee.view', $query->id) . '" class="btn btn-sm btn-primary"> <i class="fa fa-eye"></i></a>';
                }
                if(checkPermission('admin.employee.users.delete')) {
                    $links .= '&nbsp;<button class="btn btn-sm btn-danger" onclick="deleteUser($(this),'.$query->id.')"><i class="fa fa-trash"></i> </button>';
                }
                return $links;
            })
            ->escapeColumns([])
            ->toJson();
    }
    public function create(){
        if(checkPermission('admin.employee.users.create')){
            $this->loadSelect2();
            $breadcrumbData = [
                [
                    'title'=>'Dashboard',
                    'url' => route('dashboard'),
                    'active' => false,
                ],
                [
                    'title' => 'Employees',
                    'url'=> route('employee.list'),
                    'active'=> false,

                ],
                [
                    'title' => 'Create',
                    'url'=> '#',
                    'active'=> true,
                ]
            ];

            return view('Admin.Employee.create',[
                'page_title' => 'Create Employee',
                'menu' => 'employee',
                'breadcrumbData' => $breadcrumbData,
            ]);
        }else{
            return Redirect::back()->with(['msg_type'=>'error','msg'=>'you are not allowed to access']);
        }

    }

    public function edit($id){
        if(checkPermission('admin.employee.users.update')){
            if($employee = User::find($id)){
                $this->loadSelect2();
                $breadcrumbData = [
                    [
                        'title'=>'Dashboard',
                        'url' => route('dashboard'),
                        'active' => false,
                    ],
                    [
                        'title' => 'Employees',
                        'url'=> route('employee.list'),
                        'active'=> false,
                    ],
                    [
                        'title' => 'Update',
                        'url'=> '#',
                        'active'=> true,
                    ]
                ];
                return view('Admin.Employee.create',[
                    'page_title' => 'Update Employee',
                    'menu' => 'employee',
                    'breadcrumbData' => $breadcrumbData,
                    'employee' => $employee,
                ]);
            }else{
                return Redirect::back()->with(['msg_type' => 'success','msg' => 'Employee was not found']);
            }
        }else{
            return Redirect::back()->with(['msg_type'=>'error','msg'=>'you are not allowed to access']);
        }
    }
    public function view($id){
        if(checkPermission('admin.employee.users.view')){
            $breadcrumbData = [
                [
                    'title'=>'Dashboard',
                    'url' => route('dashboard'),
                    'active' => false,
                ],
                [
                    'title' => 'Employees',
                    'url'=> route('employee.list'),
                    'active'=> false,
                ],
                [
                    'title' => 'View',
                    'url'=>'',
                    'active'=> true,
                ]
            ];
            $this->setDatatableJSCSS();
            $employee = User::find($id);
            //        dd($user->saleCardListingOrders);
            if($employee){
                return view('Admin.Employee.view',[
                    'page_title' =>'Employee Detail',
                    'menu' =>'employee',
                    'employee'=> $employee,
                    'breadcrumbData'=> $breadcrumbData,
                ]);
            }
            return Redirect::back()->with(['msg_type'=>'danger','msg'=>'Employee Not Found']);
        }else{
            return Redirect::back()->with(['msg_type'=>'error','msg'=>'you are not allowed to access']);
        }

    }

    public function save(Request  $request,$id = null){
        if($id){
            $employee = User::find($id);
            if($request->name){
                $employee->update(['name'=>$request->name]);
            }
            if($request->username){
                $employee->update(['username'=>$request->username]);
            }
            if($request->email){
                $employee->update(['email'=>$request->email]);
            }
            if($request->password){
                $employee->update(['password'=> sha1($request->password)]);
            }
            if($request->bio){
                $employee->update(['bio'=> $request->bio]);
            }
//            if(empty($request->old_image_url)){
//                $employee->unlinkImage();
//            }


            // manage roles by user id
//            if($request->roles){
//                RoleUsers::where('user_id',$id)->delete();
//                foreach ($request->roles as $role_id){
//                    RoleUsers::create(['role_id' => $role_id,'user_id'=>$id]);
//                }
//            }
            return redirect('admin/employee')->with(['msg_type' => 'success','msg' => 'Employee Updated']);

        }else{
            $validator = Validator::make($request->all(),[
                'username' =>'unique:users,username',
                'email' =>'unique:users,email',
            ]);
            if($validator->fails()){
                return Redirect::back()->withErrors($validator)->withInput();
            }else{
                $request->request->add([
                    'is_employee' => 1,
                    'is_admin' => 1,
                    'active' => 1,
                    'password' => sha1($request->password),
                ]);

                $employee =  User::make($request->all());
                $employee->save();
//                if($request->hasFile('image')){
//                    $employee->uploadImage();
//                }

                // manage roles by user id
                RoleUsers::where('user_id',$employee->id)->delete();
//                foreach ($request->roles as $role_id){
                $role = RoleUsers::create(['role_id' => 5,'user_id' => $employee->id]);
//                }
                return redirect('admin/employee')->with(['msg_type' => 'success','msg' => 'Employee Created']);
            }
        }

    }
    public function delete($id){
        $response = [];
        if($user = User::find($id)){
            $user->delete();
            $response = [
                'status' => 1,
                'message' => 'Employee deleted',
            ];
        }else{
            $response = [
                'status' => 0,
                'message' => 'Employee not found'
            ];
        }
        return $response;
    }
}

resources/views/Admin/Employee/create.blade.php
@extends('Admin.layout.layout')

@section('content')
    <div class="row">
        <div class="col-12">
            <form class="" method="post" id="UserForm" action="{{ isset($employee) ?route('employee.save',$employee->id) :route('employee.save') }}" enctype="multipart/form-data">
               {{ csrf_field() }}
                <!-- Default box -->
                <div class="card card-header-custom-color">
                    <div class="card-header">
                        <h3 class="card-title">{{ isset($employee) ? 'Edit':'Create' }} Employee</h3>

                        <div class="card-tools">
                        </div>
                    </div>
                    <div class="card-body">
{{--                        <div class="form-group">--}}
{{--                            <label>Role</label>--}}
{{--                            <select required class="form-control select2bs4" multiple name="roles[]">--}}
{{--                                <option value="">Choose Role</option>--}}
{{--                                @foreach($roles as $id=> $name)--}}
{{--                                    <option value="{{ $id }}" {{ isset($designer->role_ids) && in_array($id,$designer->role_ids)  ?'selected':'' }}>{{ $name }}</option>--}}
{{--                                @endforeach--}}
{{--                            </select>--}}
{{--                        </div>--}}
                           <div class="form-group">
                               <label for="">Name</label>
                               <input required type="text" name="name" class="form-control" value="{{ isset($employee) ? $employee->name:old('name') }}" id="name" placeholder="Enter Name">
                           </div>
                        <div class="form-group">
                            <label for="">Username</label>
                            <input required type="text" name="username" class="form-control {{ $errors->first('username') ?'is-invalid':'' }}" value="{{ isset($employee) ? $employee->username:old('username') }}" id="username" placeholder="Enter Username">

                                <span  class="error invalid-feedback">{{ $errors->first('username') }}</span>

                        </div>
                        <div class="form-group">
                            <label for="">Email</label>
                            <input required type="email" name="email" class="form-control {{ $errors->first('email') ?'is-invalid':'' }}" value="{{ isset($employee) ? $employee->email:old('email') }}" id="email" placeholder="Enter Email">

                                    <span  class="error invalid-feedback">{{ $errors->first('email') }}</span>

                        </div>
                        <div class="form-group">
                            <label for="">Bio</label>
                            <textarea name="bio" class="form-control" placeholder="Enter Bio">{{ isset($employee) ? $employee->bio: old('bio') }}</textarea>
                        </div>
{{--                       <div class="form-group">--}}
{{--                                <input type="hidden" name="old_image_url" value="{{ isset($employee) ? $employee->image_url:'' }}">--}}
{{--                               <label>Choose Profile Image</label>--}}
{{--                               <br>--}}
{{--                               <div class="file btn btn-sm btn-primary" style="background-color: #dc3545 !important;">--}}
{{--                                   Choose File--}}
{{--                                   <input type="file" id="profileImage" name="image"/>--}}
{{--                               </div>--}}

{{--                               <div class="image-div" id="imagePreview" style="{{ (!isset($employee) || !$employee->check_file_exists) ?'display: none;' :'' }}">--}}
{{--                                   <br>--}}
{{--                                   <img src="{{ (isset($employee) && $employee->check_file_exists) ? $employee->image_url :'' }}" alt="Avatar" class="custom-image" style="width:100%">--}}
{{--                                   <div class="middle">--}}
{{--                                       <button class="custom-img-text btn btn-xs btn-danger" type="button" onclick="removeIMG($(this))"><i class="fa fa-trash"></i></button>--}}
{{--                                   </div>--}}
{{--                               </div>--}}
{{--                       </div>--}}
                        <div class="form-group">
                            <label for="">Password</label>
                            <input @if(!isset($employee)) required @endif type="password" name="password" class="form-control"  id="password" placeholder="Enter Password">
                            @if(isset($employee))<em>Enter password  If you have to change password </em>@endif
                        </div>
                        <div class="form-group">
                            <label for="">Confirm Password</label>
                            <input @if(!isset($employee)) required @endif type="password" name="cpassword" id="cpassword" class="form-control" placeholder="Enter Confirm Password">
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary-custom">Submit</button>
                    </div>
                </div>
                <!-- /.card -->
            </form>
        </div>
    </div>
@endsection
@push('scripts')
    <script type="text/javascript">
        $(document).ready(function () {
            //Initialize Select2 Elements
            // $('.select2bs4').select2({
            //     theme: 'bootstrap4',
            //     placeholder:'Select Roles',
            // }).on('change',function(e){
            //     $(this).valid();
            // });
            $('#UserForm').validate({
                rules: {
                    // 'roles[]':{
                    //     minlength:1
                    // },
                    password: {
                        minlength:6

                    },
                    cpassword:{
                        equalTo:'#password',
                    }
                },
                messages: {
                    name: {
                        required: "Please Enter Name",
                    },
                    username: {
                        required: "Please Enter Username",
                    },
                    email: {
                        required: "Please Enter Email",
                    },
                    password:{
                        required:'Please Enter Password',
                    },
                    cpassword:{
                        required:'Please Enter Confirm Password',
                        equalTo:'Password does not matched',
                    },
                    // 'roles[]':{
                    //     required:'Please Select Roles',
                    // },
                },
                errorElement: 'span',

            });
            // $('#profileImage').on('change',function(){
            //     var imageUrl =  readURL(this,$('#imagePreview').find('img'));
            //
            //     $('#imagePreview').show();
            // });
        });
        // function removeIMG(ele) {
        //     ele.parents('.image-div').find('.custom-image').attr('src','');
        //     ele.parents('.image-div').hide();
        //     $('input[name="old_image_url"]').val('');
        // }
        // function readURL(input,previewImageEle) {
        //     if (input.files && input.files[0]) {
        //         var reader = new FileReader();
        //         reader.onload = function (e) {
        //             $(previewImageEle).attr('src', e.target.result);
        //         }
        //         reader.readAsDataURL(input.files[0]); // convert to base64 string
        //     }
        // }function removeIMG(ele) {
        //     ele.parents('.image-div').find('.custom-image').attr('src','');
        //     ele.parents('.image-div').hide();
        //     $('input[name="old_image_url"]').val('');
        // }
        // function readURL(input,previewImageEle) {
        //     if (input.files && input.files[0]) {
        //         var reader = new FileReader();
        //         reader.onload = function (e) {
        //             $(previewImageEle).attr('src', e.target.result);
        //         }
        //         reader.readAsDataURL(input.files[0]); // convert to base64 string
        //     }
        // }
    </script>
@endpush

resources/views/Admin/Employee/view.blade.php
@extends('Admin.layout.layout')
@section('content')
        <div class="row">
            <div class="col-12">
                <!-- Default box -->
                <div class="card card-header-custom-color">
                    <div class="card-header">
                        <h3 class="card-title">Employee Detail</h3>

                        <div class="card-tools">
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12 col-sm-3">
                                <div class="info-box bg-light">
                                    <div class="info-box-content">
                                        <img src="{{ $employee->image_url }}" style="width: 100%"/>
                                        <span class="info-box-text text-center text-muted">Name</span>
                                        <span class="info-box-number text-center text-muted mb-0">{{ $employee->name }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-9">
                                <div class="row">
                                    <div class="col-12 col-sm-6">
                                        <div class="info-box bg-light">
                                            <div class="info-box-content">
                                                <span class="info-box-text text-center text-muted">Email</span>
                                                <span class="info-box-number text-center text-muted mb-0">{{ $employee->email }}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12 col-sm-6">
                                        <div class="info-box bg-light">
                                            <div class="info-box-content">
                                                <span class="info-box-text text-center text-muted">Username</span>
                                                <span class="info-box-number text-center text-muted mb-0">{{ $employee->username }}<span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12 col-sm-6">
                                        <div class="info-box bg-light">
                                            <div class="info-box-content">
                                                <span class="info-box-text text-center text-muted">Country</span>
                                                <span class="info-box-number text-center text-muted mb-0">{{ $employee->country ? $employee->country:'N/A' }}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12 col-sm-6">
                                        <div class="info-box bg-light">
                                            <div class="info-box-content">
                                                <span class="info-box-text text-center text-muted">Role</span>
                                                <span class="info-box-number text-center text-muted mb-0">{{ implode(',',$employee->role_names) }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="info-box bg-light">
                                    <div class="info-box-content">
                                        <span class="info-box-text text-center text-muted">Bio</span>
                                        <span class="info-box-number text-center text-muted mb-0">{{ $employee->bio }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
        </div>
@endsection
@push('scripts')
<script>

</script>
@endpush